# Generated by Django 5.1.2 on 2024-11-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession_location', '0002_city_state'),
        ('user_profile', '0003_remove_userprofile_location_userprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='profession',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Código de la Profesión'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='profession_location.state', verbose_name='Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
