# Generated by Django 5.1.2 on 2024-11-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profession_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('about', models.TextField(help_text='Una breve descripción sobre el usuario', verbose_name='Sobre mí')),
                ('description', models.TextField(help_text='Descripción detallada del perfil', verbose_name='Descripción')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('header', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Imagen de Perfil')),
                ('certificate', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Certificado')),
                ('portfolio1', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Portafolio 1')),
                ('portfolio2', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Portafolio 2')),
                ('portfolio3', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Portafolio 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('location', models.ForeignKey(blank=True, help_text='Departamento del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profession_location.location', verbose_name='Ubicación')),
                ('profession', models.ForeignKey(blank=True, help_text='Profesión del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profession_location.profession', verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
