# Generated by Django 5.1.2 on 2024-11-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession_location', '0002_city_state'),
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ciudad del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profession_location.city', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado o departamento del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profession_location.state', verbose_name='Estado'),
        ),
    ]
