# Generated by Django 5.1.2 on 2024-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_user_id', models.IntegerField(blank=True, help_text='ID del usuario al que pertenece el perfil marcado como favorito', null=True, verbose_name='ID del Usuario del Perfil Favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se añadió el perfil a favoritos', verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
            },
        ),
    ]
