# Generated by Django 5.1.2 on 2024-11-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favourites', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='profile',
            field=models.ForeignKey(help_text='Perfil que ha sido marcado como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='user_profile.userprofile', verbose_name='Perfil favorito'),
        ),
    ]
