# Generated by Django 5.1.2 on 2024-11-17 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favourites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(help_text='Usuario autenticado que guarda el favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que guarda como favorito'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'profile')},
        ),
    ]
