# Generated by Django 5.1.2 on 2024-11-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(help_text='Perfil del usuario al que se dirige la reseña', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='user_profile.userprofile', verbose_name='Perfil'),
        ),
    ]
